default: &default
  adapter: postgresql
  host: localhost
  username: god
  password: damn
  database: skela_courses_production

development: &development
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: god
  password: damn
  database: skela_courses_development

test: &test
  <<: *development
  database: skela_courses_test

cucumber:
  <<: *test

production:
  <<: *default
