default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: databoss
  password: Aquafina

development:
  <<: *default
  database: skela_courses_development

test: &test
  <<: *default
  database: skela_courses_test

cucumber:
  <<: *test

production:
  adapter: postgresql
  host: localhost
  username: god
  password: damn
  database: production
